---
- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install git repo
  yum:
    name: http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm
    state: present
- name: install required packages
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - git
    - curl
    - zlib
    - zlib-devel
    - gcc-c++
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - vim
    - htop
    - tree
    - ImageMagick
